### ISSUE TITLE
Make text appear and disappear again

### ISSUE THREAD

**Issue by quakberto** [marcomusy/vtkplotter#28] opened 2019-06-12 17:17 UTC
Hi, thanks for such a great tool!

I'm trying to have changing text in an animation and don't manage to properly make it appear and disappear. Consider this example:

```
from vtkplotter import Text, screenshot, Plotter

vp = Plotter(axes=0, interactive=0)

for i in [1,2,3]:
    text = Text('%03d' %i)
    # vp.actors = [text] # this produces different results
    vp.add(text)
    vp.show()
    screenshot('test_%03d.png' %i)
    vp.remove(text)
```

Output: test_000.png shows 001 instead of 002...

Thanks a lot!

**Comment by marcomusy** [comment] 2019-06-12 18:25
Hi @quakberto 
thanks!
i cannot reproduce the problem.. are you running the latest version? try
`pip install -U vtkplotter`
Also, you cannot have a test_000 with `i` in the range of [1,2,3].
This gives me the expected output:
```python
from vtkplotter import Text, screenshot, Plotter

vp = Plotter(axes=0, interactive=0)

for i in [0,1,2,3]:
    text = Text('%03d' %i, c='white')
    vp += text
    # vp += more objects..
    vp.show()
    screenshot('htest_%03d.png' %i)
    vp.remove(text)
```

![image](https://user-images.githubusercontent.com/32848391/59375824-3f925c00-8d4f-11e9-9ccc-ed0bb654bda1.png)

Let me know if it still does not work for you,
cheers
Marco

**Comment by quakberto** [comment] 2019-06-13 09:56
Hi Marco,

thanks for the quick look!

> i cannot reproduce the problem.. are you running the latest version? try
> pip install -U vtkplotter

Indeed I was one release behind, however the behaviour I get remains the same.

Your code gives me this output (I just increased the text size `...,s=10)`):
![image](https://user-images.githubusercontent.com/12528388/59422401-9be99000-8dd0-11e9-96bd-b4b4221caaa8.png)

> Also, you cannot have a test_000 with i in the range of [1,2,3].

Sorry, of course you're right, I meant test_002.png. Here's the output of the code I posted above:

![image](https://user-images.githubusercontent.com/12528388/59422981-83c64080-8dd1-11e9-8030-75b72e0087aa.png)

Notice also the difference in text color.

Let me know if I can give you any info about my environment. In any case, I guess this could well be a problem outside of vtkplotter.

Cheers

**Comment by marcomusy** [comment] 2019-06-13 10:19
that's funny... it must be something related to your python (?). In my ubuntu system with either python 2,3 your script gives the expected output.
Try maybe `Text(str(i), c='white')` and `screenshot(str(i)+'.png')`

The color difference is caused by the fact the first time the rendering window does not yet exist, so vtkplotter makes it a default grey, This is fixed by explicitly setting `c='white'`.

**Comment by quakberto** [comment] 2019-06-13 13:28
> The color difference is caused by the fact the first time the rendering window does not yet exist, so vtkplotter makes it a default grey,

Okay, that explains the grey. Still it's a bit strange that the second screenshot is also grey, as the rendering window already existed in the second iteration.

Yeah, must be something in my environment which is clearly a bit strange. For example, despite it being a clean anaconda installation on a fresh MacOS, executing the same code above with ipython gives me a segfault (in the screenshot command). Without screenshot, the rendering window is not displayed. In any case I'll try to reproduce the problem on another system soon.

Thanks for the help and I'll write here if I find out anything new in case anyone else stumbles upon a similar problem :)

**Comment by marcomusy** [comment] 2019-06-13 22:53
Hi again, I tried on my mac and YES, i can reproduce the issue! i´ll investigate that, thanks for spotting the issue, and get back to you asap.

**Comment by marcomusy** [comment] 2019-06-17 11:49
@quakberto 
I think I fixed the issue... give it a try:
```bash
git clone https://github.com/marcomusy/vtkplotter.git
cd vtkplotter
pip install .
```
then:
```python
from vtkplotter import *

#this is needed when using ipython or from jupyter:
#embedWindow(False) 

vp = Plotter(axes=0, interactive=0)

for i in [1,2,3]:
    text = Text('%03d' %i, c='white')
    vp += text
    vp += Sphere(c=i).x(i)
    vp.show()
    screenshot('test_%03d.png' %i)
    vp.remove(text)
```
![image](https://user-images.githubusercontent.com/32848391/59602227-81802100-9106-11e9-9d5d-3658a185cbf6.png)

Let me know if the issue persists,
Cheers, M.

**Comment by quakberto** [comment] 2019-06-17 15:58
Hi Marco,

nice, after updating to your new version I get the same output as you!

As your comment says, `embedWindow(False)` is needed on ipython or jupyter. Also the normal python console seems to be fine with it.

Thanks a lot for following up on the issue!

Cheers,
Marvin

**Closed** 2019-06-17 19:29 UTC
Labels: bug, help wanted
