### ISSUE TITLE
Error when closing PyQt application

### ISSUE THREAD

**Issue by hmralavi** [marcomusy/vtkplotter#51] opened 2019-09-18 08:23 UTC
I am using vtkplotter in my PyQt5 application. When I close the application, a window shows up which contains some errors I can't understand.
I also tried the qt_window.py example but I got the same error.
A screenshot of the error is attached.

Is there any way to solve this?

![error](https://user-images.githubusercontent.com/36481073/65130755-4f3ad400-da13-11e9-8fbd-b9513a7e9484.png)

**Comment by marcomusy** [comment] 2019-09-18 10:54
Hi, unfortunately I cannot reproduce the problem and I don't have an easy fix... the issue seems related to Windows OS with Intel graphics drivers:
https://discourse.vtk.org/t/wglmakecurrent-failed-in-makecurrent/1516
https://discourse.vtk.org/t/visible-cell-selection-hardwareselector-py-example-is-not-working-reliably/1262/12
https://discourse.vtk.org/t/problem-with-view-update-since-intel-uhd-graphics-620-driver-update/1224/5

You may try to:
- run some standard vtk examples to see if you still get the error:
https://vtk.org/Wiki/VTK/Examples/Python/Widgets/EmbedPyQt

- rebuild VTK with different flags (uncommenting the lines as indicated in the above threads).

**Comment by hmralavi** [comment] 2019-09-18 12:56
It doesn't seem to be an intel graphic issue because:

1. I tested the [https://vtk.org/Wiki/VTK/Examples/Python/Widgets/EmbedPyQt](url) on both intel and nvidia graphics and got **no errors**.

2. I tested the [https://github.com/marcomusy/vtkplotter/blob/master/examples/other/qt_window.py](url) on both intel and nvidia graphics and got the **same errors** as I mentioned.

I also tried to use this suggestion: [https://discourse.vtk.org/t/visible-cell-selection-hardwareselector-py-example-is-not-working-reliably/1262/6](url), but I couldn't find the _**vtkWin32OpenGLRenderWindow.cxx**_ file.

**Comment by marcomusy** [comment] 2019-09-18 16:42
OK, I will see if I can reproduce it on a windows machine.

**Comment by RubendeBruin** [comment] 2019-09-26 17:16
Hi hmralavi, 

I had the same problem. Running the following when closing the qt application solved the problem for me:

during the qt-onClose event:

 def shutdown_qt(self):
        """Stops the renderer such that the application can close without issues"""

        if self.vtkWidget:
            ren = self.vtkWidget.GetRenderWindow()
            iren = ren.GetInteractor()
            ren.Finalize()
            iren.TerminateApp()

**Comment by marcomusy** [comment] 2019-09-26 17:18
Thanks @RubendeBruin for addressing this! Unfortunately I didn't have much time lately to investigate it!

**Comment by hmralavi** [comment] 2019-09-30 11:53
@RubendeBruin thanks for the tip.
I also use the following command in Qt closing event and the problem solves.
`self.vtkWidget.close()`

**Closed** 2019-10-08 11:32 UTC
Labels: bug
